version: '3'
services:
  first:
    container_name: first
    image: first
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4001:3003
  second:
    container_name: second
    image: second
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4002:3003
  third:
    container_name: third
    image: third
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4003:3003
  fourth:
    container_name: fourth
    image: fourth
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4004:3003
  fifth:
    container_name: fifth
    image: fifth
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4005:3003
  six:
    container_name: six
    image: six
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4006:3003
  seven:
    container_name: seven
    image: seven
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4007:3003
  eight:
    container_name: eight
    image: eight
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4008:3003
  nine:
    container_name: nine
    image: nine
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4009:3003
  ten:
    container_name: ten
    image: ten
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4010:3003
  nginx:
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - first
      - second
      - third
      - fourth
      - fifth
      - six
      - seven
      - eight
      - nine
      - ten